/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CreateProjectController;
import java.awt.Frame;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Simulator;

/**
 *
 * @author G11
 */
public class CreateProjectUI extends javax.swing.JDialog {

    /**
     * Frame parent.
     */
    private Frame parent;
    /**
     * Create project controller.
     */
    private CreateProjectController controller;
    /**
     *File chooser associated with file import.
     */
    private JFileChooser filechooser;

    /**
     * Creates new form CreateProjectUI
     */
    public CreateProjectUI(java.awt.Frame parent, boolean modal, Simulator simulator) {
        super(parent, "Create Project", modal);
        this.controller = new CreateProjectController(simulator);
        this.parent = parent;
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jBtn_import_Project = new javax.swing.JButton();
        fileField = new javax.swing.JTextField();
        jBtn_file_chooser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_import_Project.setText("Import Project");
        jBtn_import_Project.setEnabled(false);
        jBtn_import_Project.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtn_import_ProjectActionPerformed(evt);
            }
        });

        fileField.setEditable(false);

        jBtn_file_chooser.setText("Select File");
        jBtn_file_chooser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtn_file_chooserActionPerformed(evt);
            }
        });

        jLabel1.setText("Path to project file:");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtn_import_Project)
                            .addComponent(fileField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn_file_chooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_file_chooser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_import_Project)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_file_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_file_chooserActionPerformed
        this.filechooser = new JFileChooser();
        int resposta = this.filechooser.showSaveDialog(this.parent);
        switch (resposta)
        {
            case JFileChooser.APPROVE_OPTION:
            fileField.setText(filechooser.getSelectedFile().getAbsolutePath());
            jBtn_import_Project.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_jBtn_file_chooserActionPerformed

    private void jBtn_import_ProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_import_ProjectActionPerformed
        try {
            controller.newProject();
            String path = fileField.getText();
            this.controller.setPath(path);
            JOptionPane.showMessageDialog(parent,"Project successfully created.","",JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this.parent, ex.getMessage(), "CreateProject", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_import_ProjectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fileField;
    private javax.swing.JButton jBtn_file_chooser;
    private javax.swing.JButton jBtn_import_Project;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
