package model;

import static org.junit.Assert.*;
import org.junit.Test;

/**
 *
 * @author G11
 */
public class ImportXMLTest {

    /**
     * Test of importProject method, of class ImportXML.
     */
    @Test
    public void testImportProject() {
        System.out.println("importProject");
        Project project = new Project();
        String filePath = "./test/xml/Project.xml";
        ImportXML instance = new ImportXML();
        instance.importProject(project, filePath);

        String expResult = "Name: TestSet03\n"
                + "Description: 5 node test set\n"
                + "Roadmap: 5 intersections, 12 roads\n"
                + "n0 (0): \n"
                + "	Road name: E01-n0-n2\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: 20.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,718 º\n"
                + "			Lenght: 3200,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 196.0 m\n"
                + "			Angle: -0,859 º\n"
                + "			Lenght: 6400,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "\n"
                + "	Road name: \"A01\"-n0-n1\n"
                + "	Typology: highway\n"
                + "	Toll: 12.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,000 º\n"
                + "			Lenght: 25000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 2000 vehicles\n"
                + "\n"
                + "n1 (1): \n"
                + "	Road name: \"A01\"-n1-n0\n"
                + "	Typology: highway\n"
                + "	Toll: 12.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,000 º\n"
                + "			Lenght: 25000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 2000 vehicles\n"
                + "\n"
                + "	Road name: \"A01\"-n1-n3\n"
                + "	Typology: highway\n"
                + "	Toll: 4.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,286 º\n"
                + "			Lenght: 20000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 1500 vehicles\n"
                + "\n"
                + "n2 (2): \n"
                + "	Road name: E01-n2-n0\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: -20.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 196.0 m\n"
                + "			Angle: -0,859 º\n"
                + "			Lenght: 6400,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,718 º\n"
                + "			Lenght: 3200,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "\n"
                + "	Road name: E01-n2-n3\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,859 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 350 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 150.0 m\n"
                + "			Angle: 0,573 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "\n"
                + "	Road name: E06-n2-n4\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 2.7777777777777777m/s\n"
                + "	Wind orientation: -15.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 150 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 350.0 m\n"
                + "			Angle: -2,291 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 100 vehicles\n"
                + "\n"
                + "n3 (3): \n"
                + "	Road name: E01-n3-n2\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 150.0 m\n"
                + "			Angle: 0,573 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,859 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 350 vehicles\n"
                + "\n"
                + "	Road name: E01-n3-n4\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 200.0 m\n"
                + "			Angle: 1,146 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 300 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 400.0 m\n"
                + "			Angle: -1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "\n"
                + "	Road name: \"A01\"-n3-n1\n"
                + "	Typology: highway\n"
                + "	Toll: 4.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,286 º\n"
                + "			Lenght: 20000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 1500 vehicles\n"
                + "\n"
                + "n4 (4): \n"
                + "	Road name: E01-n4-n3\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 400.0 m\n"
                + "			Angle: -1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 200.0 m\n"
                + "			Angle: 1,146 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 300 vehicles\n"
                + "\n"
                + "	Road name: E06-n4-n2\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 2.7777777777777777m/s\n"
                + "	Wind orientation: 15.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 350.0 m\n"
                + "			Angle: -2,291 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 100 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 150 vehicles\n"
                + "\n"
                + "List of Vehicles:\n"
                + "	Name: Dummy01\n"
                + "	Description: Dummy teste vehicle 01\n"
                + "	Type: car\n"
                + "	Fuel: gasoline\n"
                + "	Mass: 2400.0 Kg\n"
                + "	Load: 420.0 Kg\n"
                + "	Drag Coefficient: 0.38\n"
                + "	Frontal Area: 2.4 m\n"
                + "	RRC: 0.01\n"
                + "	Wheel Size: 0.7 m\n"
                + "	Velocity Limits:\n"
                + "		Highway: 27.77777777777778 m/s\n"
                + "	RPM Minimum: 1000\n"
                + "	RPM Maximum: 5500\n"
                + "	Final Drive: 2.6 m\n"
                + "	Gearbox:\n"
                + "		1 - Ratio: 3.5\n"
                + "		2 - Ratio: 2.5\n"
                + "		3 - Ratio: 1.9\n"
                + "		4 - Ratio: 1.2\n"
                + "		5 - Ratio: 0.8\n"
                + "	List of throttles:\n"
                + "		Percentage: 25%\n"
                + "		List of regimes:\n"
                + "			Torque: 105\n"
                + "			RPM lower interval: 1000\n"
                + "			RPM higher interval: 2499\n"
                + "			SFC: 8.2\n"
                + "\n"
                + "			Torque: 115\n"
                + "			RPM lower interval: 2500\n"
                + "			RPM higher interval: 3999\n"
                + "			SFC: 6.2\n"
                + "\n"
                + "			Torque: 100\n"
                + "			RPM lower interval: 4000\n"
                + "			RPM higher interval: 5500\n"
                + "			SFC: 10.2\n"
                + "\n"
                + "		Percentage: 50%\n"
                + "		List of regimes:\n"
                + "			Torque: 135\n"
                + "			RPM lower interval: 1000\n"
                + "			RPM higher interval: 2499\n"
                + "			SFC: 5.2\n"
                + "\n"
                + "			Torque: 150\n"
                + "			RPM lower interval: 2500\n"
                + "			RPM higher interval: 3999\n"
                + "			SFC: 3.2\n"
                + "\n"
                + "			Torque: 130\n"
                + "			RPM lower interval: 4000\n"
                + "			RPM higher interval: 5500\n"
                + "			SFC: 8.2\n"
                + "\n"
                + "		Percentage: 100%\n"
                + "		List of regimes:\n"
                + "			Torque: 220\n"
                + "			RPM lower interval: 1000\n"
                + "			RPM higher interval: 2499\n"
                + "			SFC: 2.2\n"
                + "\n"
                + "			Torque: 250\n"
                + "			RPM lower interval: 2500\n"
                + "			RPM higher interval: 3999\n"
                + "			SFC: 1.2\n"
                + "\n"
                + "			Torque: 190\n"
                + "			RPM lower interval: 4000\n"
                + "			RPM higher interval: 5500\n"
                + "			SFC: 4.2\n"
                + "\n"
                + "	Name: Dummy02\n"
                + "	Description: Dummy teste vehicle 02\n"
                + "	Type: car\n"
                + "	Fuel: gasoline\n"
                + "	Mass: 1400.0 Kg\n"
                + "	Load: 320.0 Kg\n"
                + "	Drag Coefficient: 0.3\n"
                + "	Frontal Area: 1.8 m\n"
                + "	RRC: 0.01\n"
                + "	Wheel Size: 0.5 m\n"
                + "	RPM Minimum: 1000\n"
                + "	RPM Maximum: 5500\n"
                + "	Final Drive: 2.6 m\n"
                + "	Gearbox:\n"
                + "		1 - Ratio: 3.5\n"
                + "		2 - Ratio: 2.7\n"
                + "		3 - Ratio: 1.9\n"
                + "		4 - Ratio: 1.3\n"
                + "		5 - Ratio: 0.7\n"
                + "	List of throttles:\n"
                + "		Percentage: 25%\n"
                + "		List of regimes:\n"
                + "			Torque: 85\n"
                + "			RPM lower interval: 1000\n"
                + "			RPM higher interval: 2499\n"
                + "			SFC: 8.2\n"
                + "\n"
                + "			Torque: 95\n"
                + "			RPM lower interval: 2500\n"
                + "			RPM higher interval: 3999\n"
                + "			SFC: 6.2\n"
                + "\n"
                + "			Torque: 80\n"
                + "			RPM lower interval: 4000\n"
                + "			RPM higher interval: 5500\n"
                + "			SFC: 10.2\n"
                + "\n"
                + "		Percentage: 50%\n"
                + "		List of regimes:\n"
                + "			Torque: 135\n"
                + "			RPM lower interval: 1000\n"
                + "			RPM higher interval: 2499\n"
                + "			SFC: 5.2\n"
                + "\n"
                + "			Torque: 150\n"
                + "			RPM lower interval: 2500\n"
                + "			RPM higher interval: 3999\n"
                + "			SFC: 3.2\n"
                + "\n"
                + "			Torque: 140\n"
                + "			RPM lower interval: 4000\n"
                + "			RPM higher interval: 5500\n"
                + "			SFC: 8.2\n"
                + "\n"
                + "		Percentage: 100%\n"
                + "		List of regimes:\n"
                + "			Torque: 180\n"
                + "			RPM lower interval: 1000\n"
                + "			RPM higher interval: 2499\n"
                + "			SFC: 2.2\n"
                + "\n"
                + "			Torque: 200\n"
                + "			RPM lower interval: 2500\n"
                + "			RPM higher interval: 3999\n"
                + "			SFC: 1.2\n"
                + "\n"
                + "			Torque: 180\n"
                + "			RPM lower interval: 4000\n"
                + "			RPM higher interval: 5500\n"
                + "			SFC: 4.2\n"
                + "\n"
                + "	Name: ElectricDummy\n"
                + "	Description: Electric Dummy teste vehicle\n"
                + "	Type: car\n"
                + "	Fuel: electric\n"
                + "	Mass: 1500.0 Kg\n"
                + "	Load: 320.0 Kg\n"
                + "	Drag Coefficient: 0.32\n"
                + "	Frontal Area: 1.8 m\n"
                + "	RRC: 0.01\n"
                + "	Wheel Size: 0.5 m\n"
                + "	RPM Minimum: 0\n"
                + "	RPM Maximum: 10500\n"
                + "	Final Drive: 2.6 m\n"
                + "	Energy Regeneration Ratio: 0.8 \n"
                + "	Gearbox:\n"
                + "		1 - Ratio: 1.0\n"
                + "	List of throttles:\n"
                + "		Percentage: 25%\n"
                + "		List of regimes:\n"
                + "			Torque: 85\n"
                + "			RPM lower interval: 0\n"
                + "			RPM higher interval: 3499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 80\n"
                + "			RPM lower interval: 3500\n"
                + "			RPM higher interval: 4499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 75\n"
                + "			RPM lower interval: 4500\n"
                + "			RPM higher interval: 5499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 70\n"
                + "			RPM lower interval: 5500\n"
                + "			RPM higher interval: 6499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 65\n"
                + "			RPM lower interval: 6500\n"
                + "			RPM higher interval: 7499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 55\n"
                + "			RPM lower interval: 7500\n"
                + "			RPM higher interval: 8499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 45\n"
                + "			RPM lower interval: 8500\n"
                + "			RPM higher interval: 9499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 30\n"
                + "			RPM lower interval: 9500\n"
                + "			RPM higher interval: 10500\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "		Percentage: 50%\n"
                + "		List of regimes:\n"
                + "			Torque: 150\n"
                + "			RPM lower interval: 0\n"
                + "			RPM higher interval: 3499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 145\n"
                + "			RPM lower interval: 3500\n"
                + "			RPM higher interval: 4499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 140\n"
                + "			RPM lower interval: 4500\n"
                + "			RPM higher interval: 5499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 130\n"
                + "			RPM lower interval: 5500\n"
                + "			RPM higher interval: 6499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 120\n"
                + "			RPM lower interval: 6500\n"
                + "			RPM higher interval: 7499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 105\n"
                + "			RPM lower interval: 7500\n"
                + "			RPM higher interval: 8499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 80\n"
                + "			RPM lower interval: 8500\n"
                + "			RPM higher interval: 9499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 60\n"
                + "			RPM lower interval: 9500\n"
                + "			RPM higher interval: 10500\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "		Percentage: 100%\n"
                + "		List of regimes:\n"
                + "			Torque: 250\n"
                + "			RPM lower interval: 0\n"
                + "			RPM higher interval: 3499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 240\n"
                + "			RPM lower interval: 3500\n"
                + "			RPM higher interval: 4499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 230\n"
                + "			RPM lower interval: 4500\n"
                + "			RPM higher interval: 5499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 215\n"
                + "			RPM lower interval: 5500\n"
                + "			RPM higher interval: 6499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 180\n"
                + "			RPM lower interval: 6500\n"
                + "			RPM higher interval: 7499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 140\n"
                + "			RPM lower interval: 7500\n"
                + "			RPM higher interval: 8499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 110\n"
                + "			RPM lower interval: 8500\n"
                + "			RPM higher interval: 9499\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "			Torque: 80\n"
                + "			RPM lower interval: 9500\n"
                + "			RPM higher interval: 10500\n"
                + "			SFC: 0.0\n"
                + "\n"
                + "";

        String result = project.toString();
        assertEquals(expResult, result);
    }

    /**
     * Test of importRoads method, of class ImportXML.
     */
    @Test
    public void testImportRoads() {
        System.out.println("importRoads");
        Project project = new Project();
        project.setName("Project");
        project.setDescription("Description");
        String filePath = "./test/xml/Network.xml";
        ImportXML instance = new ImportXML();
        instance.importRoads(project, filePath);

        String expResult = ""
                + "Name: Project\n"
                + "Description: Description\n"
                + "Roadmap: 5 intersections, 12 roads\n"
                + "n0 (0): \n"
                + "	Road name: E01-n0-n2\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: 20.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,718 º\n"
                + "			Lenght: 3200,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 196.0 m\n"
                + "			Angle: -0,859 º\n"
                + "			Lenght: 6400,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "\n"
                + "	Road name: \"A01\"-n0-n1\n"
                + "	Typology: highway\n"
                + "	Toll: 12.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,000 º\n"
                + "			Lenght: 25000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 2000 vehicles\n"
                + "\n"
                + "n1 (1): \n"
                + "	Road name: \"A01\"-n1-n0\n"
                + "	Typology: highway\n"
                + "	Toll: 12.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,000 º\n"
                + "			Lenght: 25000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 2000 vehicles\n"
                + "\n"
                + "	Road name: \"A01\"-n1-n3\n"
                + "	Typology: highway\n"
                + "	Toll: 4.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,286 º\n"
                + "			Lenght: 20000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 1500 vehicles\n"
                + "\n"
                + "n2 (2): \n"
                + "	Road name: E01-n2-n0\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: -20.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 196.0 m\n"
                + "			Angle: -0,859 º\n"
                + "			Lenght: 6400,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,718 º\n"
                + "			Lenght: 3200,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "\n"
                + "	Road name: E01-n2-n3\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,859 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 350 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 150.0 m\n"
                + "			Angle: 0,573 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "\n"
                + "	Road name: E06-n2-n4\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 2.7777777777777777m/s\n"
                + "	Wind orientation: -15.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 150 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 350.0 m\n"
                + "			Angle: -2,291 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 100 vehicles\n"
                + "\n"
                + "n3 (3): \n"
                + "	Road name: E01-n3-n2\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 150.0 m\n"
                + "			Angle: 0,573 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 200 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,859 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 350 vehicles\n"
                + "\n"
                + "	Road name: E01-n3-n4\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: -5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 200.0 m\n"
                + "			Angle: 1,146 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 300 vehicles\n"
                + "		Segment: 2\n"
                + "			Initial Height: 400.0 m\n"
                + "			Angle: -1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "\n"
                + "	Road name: \"A01\"-n3-n1\n"
                + "	Typology: highway\n"
                + "	Toll: 4.0\n"
                + "	Wind speed: 0.8333333333333334m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 0,286 º\n"
                + "			Lenght: 20000,000 m\n"
                + "			Minimum velocity: 13.88888888888889 m/s\n"
                + "			Maximum velocity: 33.333333333333336 m/s\n"
                + "			Maximum number of vehicles: 1500 vehicles\n"
                + "\n"
                + "n4 (4): \n"
                + "	Road name: E01-n4-n3\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 1.3888888888888888m/s\n"
                + "	Wind orientation: 5.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 400.0 m\n"
                + "			Angle: -1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 250 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 200.0 m\n"
                + "			Angle: 1,146 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 300 vehicles\n"
                + "\n"
                + "	Road name: E06-n4-n2\n"
                + "	Typology: regular road\n"
                + "	Toll: 0.0\n"
                + "	Wind speed: 2.7777777777777777m/s\n"
                + "	Wind orientation: 15.0º\n"
                + "	List of segments:\n"
                + "		Segment: 2\n"
                + "			Initial Height: 350.0 m\n"
                + "			Angle: -2,291 º\n"
                + "			Lenght: 5000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 100 vehicles\n"
                + "		Segment: 1\n"
                + "			Initial Height: 100.0 m\n"
                + "			Angle: 1,432 º\n"
                + "			Lenght: 10000,000 m\n"
                + "			Minimum velocity: 0.0 m/s\n"
                + "			Maximum velocity: 25.0 m/s\n"
                + "			Maximum number of vehicles: 150 vehicles\n"
                + "\n"
                + "List of Vehicles:\n"
                + "";

        String result = project.toString();
        assertEquals(expResult, result);
    }

    /**
     * Test of importSimulation method, of class ImportXML.
     */
    @Test
    public void testImportSimulation() {
        System.out.println("importSimulation");
        Project project = new Project();
        String filePath = "./test/xml/Project.xml";
        ImportXML instance = new ImportXML();
        instance.importProject(project, filePath);

        Simulation simulation = new Simulation(project);
        filePath = "./test/xml/Simulation.xml";
        instance.importSimulation(simulation, filePath);

        String expResult = ""
                + "Name: TestSet03\n"
                + "Description: simulation test set with electric vehicle\n"
                + "List of Traffic:\n"
                + "	Begin node: n0\n"
                + "	End node: n4\n"
                + "	Vehicle: Dummy01\n"
                + "	Arrival Rate: 10\n"
                + "\n"
                + "	Begin node: n0\n"
                + "	End node: n4\n"
                + "	Vehicle: ElectricDummy\n"
                + "	Arrival Rate: 15\n"
                + "\n"
                + "	Begin node: n0\n"
                + "	End node: n4\n"
                + "	Vehicle: Dummy02\n"
                + "	Arrival Rate: 30\n"
                + "\n"
                + "	Begin node: n1\n"
                + "	End node: n4\n"
                + "	Vehicle: Dummy01\n"
                + "	Arrival Rate: 10\n"
                + "\n"
                + "	Begin node: n1\n"
                + "	End node: n4\n"
                + "	Vehicle: Dummy02\n"
                + "	Arrival Rate: 30\n"
                + "\n"
                + "	Begin node: n3\n"
                + "	End node: n1\n"
                + "	Vehicle: Dummy01\n"
                + "	Arrival Rate: 5\n"
                + "\n"
                + "	Begin node: n3\n"
                + "	End node: n1\n"
                + "	Vehicle: ElectricDummy\n"
                + "	Arrival Rate: 25\n"
                + "\n"
                + "	Begin node: n4\n"
                + "	End node: n1\n"
                + "	Vehicle: ElectricDummy\n"
                + "	Arrival Rate: 20\n"
                + "\n";

        String result = simulation.toString();
        assertEquals(expResult, result);
    }

}
